namespace BolWallet.Bolnformation
{
    public static class GeneratedDocumentsInformation
    {
        public const string Title = "Generated Documents Information";
        public const string Description =
            "These documents are generated by BOL for certification identity purposes. We have three documents:" +
            "<ul>" +
            "<li>Certification Matrix</li>" +
            "<li>Identification Matrix</li>" +
            "<li>Citizenship Matrix</li>" +
            "</ul>";
        public const string Content =
            "For more information, visit " +
            "<a href='https://1bol.org/' target='_blank' style='color: blue; text-decoration: underline;'>BOL's official website</a>. <br/><br/>";
    }
}
