global using BolWallet.Models;
global using BolWallet.Services;
global using BolWallet.ViewModels;
global using BolWallet.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Collections;
global using System.Text.Json;
global using BolWallet.Services.Abstractions;
